FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore \
    src/AppKm/Modules/Athletes/AppKm.Athletes.Api/AppKm.Athletes.Api.csproj

RUN dotnet publish \
    src/AppKm/Modules/Athletes/AppKm.Athletes.Api/AppKm.Athletes.Api.csproj \
    --configuration Release \
    --output /app/publish \
    --no-restore \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

ENV ASPNETCORE_HTTP_PORTS=8080
ENV DOTNET_EnableDiagnostics=0

EXPOSE 8080

COPY --from=build /app/publish .

USER app

ENTRYPOINT ["dotnet", "AppKm.Athletes.Api.dll"]
