name: app_km_prototipo1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.2
  app_links: ^7.1.0
  flutter_secure_storage: 10.3.1
  signalr_netcore: ^1.4.3
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
