// <auto-generated />
using System;
using AppKm.Athletes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppKm.Athletes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AthleteDbContext))]
    [Migration("20260819041924_AddPointTransactions")]
    partial class AddPointTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppKm.Athletes.Domain.Aggregates.AthleteActivities.AthleteActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<double>("DistanceKilometers")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_kilometers");

                    b.Property<int>("ElapsedTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time_seconds");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time_seconds");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_local");

                    b.Property<DateTimeOffset>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("strava_activity_id");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "StravaActivityId")
                        .IsUnique()
                        .HasDatabaseName("UX_athlete_activities_athlete_id_strava_activity_id");

                    b.ToTable("athlete_activities", "athletes");
                });

            modelBuilder.Entity("AppKm.Athletes.Domain.Aggregates.Athletes.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("athletes", "athletes");
                });

            modelBuilder.Entity("AppKm.Athletes.Domain.Aggregates.PointTransactions.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AthleteActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_activity_id");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "AthleteActivityId", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_point_transactions_athlete_activity_type");

                    b.ToTable("point_transactions", "athletes");
                });

            modelBuilder.Entity("AppKm.Athletes.Domain.Aggregates.StravaConnections.StravaConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_encrypted");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at_utc");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_id");

                    b.Property<DateTimeOffset>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at_utc");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint")
                        .HasColumnName("strava_athlete_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.HasIndex("StravaAthleteId")
                        .IsUnique();

                    b.ToTable("strava_connections", "athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
