namespace AppKm.Athletes.Application.Interfaces;

public sealed record StravaActivityResult(
    long Id,
    string Name,
    string SportType,
    double DistanceMeters,
    DateTimeOffset StartDateUtc,
    DateTime StartDateLocal,
    int ElapsedTimeSeconds,
    int MovingTimeSeconds,
    bool Manual = false,
    bool Flagged = false,
    double? AverageSpeedMetersPerSecond = null,
    double? MaxSpeedMetersPerSecond = null,
    double? TotalElevationGainMeters = null,
    double? ElevationHighMeters = null,
    double? ElevationLowMeters = null,
    bool HasHeartRate = false,
    bool DeviceWatts = false,
    double? AverageWatts = null,
    double? AverageHeartRate = null,
    double? AverageCadence = null,
    string? DeviceName = null,
    bool Trainer = false,
    long? UploadId = null,
    string? ExternalId = null);
